apiVersion: v1
kind: Secret
metadata:
  name: umf-gravitino-secret
type: Opaque
stringData:
  METADATA_STORE_JDBC_USER: gravitino
  METADATA_STORE_JDBC_PASSWORD: password
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: minio123
