apiVersion: v1
kind: Service
metadata:
  name: umf-gravitino
  labels:
    app: umf-gravitino
spec:
  type: NodePort
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      nodePort: 30190
      protocol: TCP
  selector:
    app: umf-gravitino
