apiVersion: v1
kind: PersistentVolume
metadata:
  name: om-mysql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/data/om-mysql-pv"  # Adjust the host path as needed
