apiVersion: apps/v1
kind: Deployment
metadata:
  name: fq-dbt-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fq-dbt-runner
  template:
    metadata:
      labels:
        app: fq-dbt-runner
    spec:
      containers:
        - name: fq-dbt-runner
          image: fq-dbt-runner:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: fq-dbt-runner-config
            - secretRef:
                name: fq-dbt-runner-secrets
          resources:
            requests:
              cpu: 250m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
