apiVersion: v1
kind: Service
metadata:
  name: fq-minio-console
  labels:
    app: fq-minio
spec:
  type: NodePort
  ports:
    - name: https
      port: 9001
      nodePort: 30991
      targetPort: 9001
      protocol: TCP
  selector:
    app: fq-minio
