apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fq

resources:
  - fq-minio-console-service.yml
  - fq-minio-deployment.yml
  - fq-minio-egress-network-policy.yml
  - fq-minio-ingress-network-policy.yml
  - fq-minio-pv.yml
  - fq-minio-pvc.yml
  - fq-minio-service.yml
