apiVersion: v1
kind: Service
metadata:
  name: moat
  namespace: aix
spec:
  type: NodePort
  selector:
    app: moat
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 32080
