apiVersion: v1
kind: PersistentVolume
metadata:
  name: om-airflow-dags-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/data/om-airflow-dags-pv"
