apiVersion: apps/v1
kind: Deployment
metadata:
  name: fq-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fq-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fq-mysql
    spec:
      containers:
      - image: mysql:8.0.28-oracle 
        name: mysql
        env:
          - name: MYSQL_ROOT_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: fq-mysql-storage
            mountPath: "/data"
      volumes:
        - name: fq-mysql-storage
          persistentVolumeClaim:
            claimName: fq-mysql-pvc

