apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fq

resources:
  - fq-mysql-pv.yml
  - fq-mysql-pvc.yml
  - fq-mysql-deployment.yml
  - fq-mysql-egress-network-policy.yml
  - fq-mysql-ingress-network-policy.yml
  - fq-mysql-service.yml
