#Gravitino currently supports only Trino 435-439
connector.name=gravitino
gravitino.uri=http://gravitino:8090
gravitino.auth-token=my-secret-token  # (Optional if authentication is enabled)
gravitino.metalake=default_metalake
# If using MinIO (S3-compatible storage)
hive.s3.aws-access-key=minio
hive.s3.aws-secret-key=minio123
hive.s3.endpoint=http://minio:9000
hive.s3.path-style-access=true
hive.s3.ssl.enabled=false
