connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://<ICEBERG_REST_SERVER>:8181
iceberg.rest-catalog.warehouse=s3://your-bucket-name/path/
iceberg.rest-catalog.credentials-provider=org.apache.iceberg.rest.auth.SimpleBearerAuthCredentialsProvider
iceberg.rest-catalog.token=<YOUR_ACCESS_TOKEN>

