connector.name=iceberg
iceberg.catalog.type=nessie
#iceberg.nessie.uri=http://nessie:19120/api/v1
iceberg.nessie-catalog.uri=http://nessie:19120/api/v2
iceberg.nessie-catalog.default-warehouse-dir=s3a://hive/warehouse/
iceberg.nessie-catalog.ref=main
iceberg.nessie-catalog.client-api-version=V2

s3.endpoint=http://minio:9000
s3.aws-access-key=minio
s3.aws-secret-key=minio123
s3.region=us-east-1
fs.hadoop.enabled=false
fs.native-s3.enabled=true
s3.path-style-access=true
iceberg.file-format=PARQUET