apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: aix
type: Opaque
stringData:
  MYSQL_DATABASE: "moat"
  MYSQL_USER: "moat_user"
  MYSQL_PASSWORD: "change-me"
  MYSQL_ROOT_PASSWORD: "change-me-root"
