apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fq

resources:
  - fq-gravitino-deployment.yml
  - fq-gravitino-service.yml
  - fq-gravitino-egress-network-policy.yml
  - fq-gravitino-ingress-network-policy.yml
