apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-gateway
  labels:
    app: trino-gateway
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: trino-gateway
  template:
    metadata:
      labels:
        app: trino-gateway
    spec:
      containers:
        - name: trino-gateway
          #image: trinodb/trino-gateway:latest
          image: docker.io/vjain143/fq-trino-gateway:1.15.0
          ports:
            - containerPort: 8080  # Adjust if your application runs on a different port
          env:
            - name: JAVA_OPTS
              value: "-XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/trino-gateway/config.yaml
              subPath: config.yaml
            - name: config-volume
              mountPath: /etc/trino-gateway/selfSignKey.pem
              subPath: selfSignKey.pem
            - name: config-volume
              mountPath: /etc/trino-gateway/selfSignCert.pem
              subPath: selfSignCert.pem
      volumes:
        - name: config-volume
          configMap:
            name: trino-gateway-config