apiVersion: v1
kind: PersistentVolume
metadata:
  name: om-server-logs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/data/om-server-logs-volume"  # Adjust the host path as needed
