serverConfig:
  port: 8080  # Adjust based on your setup

authentication:
  form:
    selfSignKeyPair:
      privateKeyRsa: "/etc/trino-gateway/selfSignKey.pem"
      publicKeyRsa: "/etc/trino-gateway/selfSignCert.pem"
      
form-auth:
  enabled: true
  public-key-file: /path/to/gateway-public.key

  #defaultType: "BASIC"  # Options: BASIC, FORM, OAUTH
  #form:
   # selfSignKeyPair: "/etc/trino-gateway/selfSignKey.pem"  # Required for self-signed JWT authentication
    #ldapConfigPath: "/path/to/ldap-config.yaml"  # Optional: Required if using LDAP authentication

routing:
  asyncTimeout: 3000ms
  addXForwardedHeaders: true

monitor:
  metricsEndpoint: "/metrics"

dataStore:
  #jdbc:mysql:mysql:3306/gateway?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
  jdbcUrl: "jdbc:mysql://mysql:3306/gateway?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"  # Replace with actual database URL
  driver: "com.mysql.cj.jdbc.Driver"  # Use "com.mysql.cj.jdbc.Driver" for MySQL, "org.postgresql.Driver" for PostgreSQL
  user: "gateway"
  password: "gateway123"
  runMigrationsEnabled: true
  queryHistoryHoursRetention: 24
