apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: umf

resources:
  - umf-mysql-secret.yml
  - umf-mysql-pv.yml
  - umf-mysql-pvc.yml
  - umf-mysql-deployment.yml
  - umf-mysql-service.yml
