apiVersion: v1
kind: Secret
metadata:
  name: umf-mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: umf_gravitino_db
  MYSQL_USER: gravitino
  MYSQL_PASSWORD: password
