connector_type: openmetadata
openmetadata:
  server_api: "http://om-server.openmetadata.svc.cluster.local:8585/api"
  auth:
    mode: "login"
    email: "admin@open-metadata.org"
    password: "admin"
    jwt_token: ""
  filters:
    table_fqn: ""
    table_fqn_prefix: "fq_trino.hms_db.fq_dbt."
    limit: 500
    fields: "tags,owners,domains,dataProducts"
  moat:
    platform: "trino"
