logger.root_level: "INFO"

flask.secret_key: "$FLASK_SECRET_KEY"
flask.environment: "Production"

database.protocol: "mysql+pymysql"
database.user: "moat_user"
database.password: "$DATABASE_PASSWORD"
database.host: "mysql"
database.port: "3306"
database.database: "moat"

bundle_generator.temp_directory: /tmp
bundle_generator.static_rego_file_path: "/opt/policies"
bundler.bundle_directory: "/opt/moat/bundles"
bundler.platform_specific_bundles: "true"

api.healthcheck.auth_method: none
api.scim.auth_method: none
api.connectors.auth_method: none

api.opa.auth_method: api-key
api.opa.api_key: bearer-token

worker.interval_s: "5"

connectors_ui.config_directory: "/opt/moat/runtime/connectors"
connectors_ui.openmetadata_default_fields: "tags,owners,domains,dataProducts"
connectors_ui.openmetadata_default_limit: "100"
connectors_ui.openmetadata_timeout_seconds: "30"
connectors_ui.default_moat_platform: "trino"
