apiVersion: v1
kind: Service
metadata:
  name: querybook
spec:
  selector:
    app: querybook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10001
      nodePort: 30001
  type: NodePort