apiVersion: apps/v1
kind: Deployment
metadata:
  name: fq-hms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fq-hms
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fq-hms
    spec:
      containers:
      - name: hive-metastore
        image: vjain143/hive-metastore:4.2.0
        env:
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            value: password
          - name: MINIO_ROOT_USER
            value: minio
          - name: MINIO_ROOT_PASSWORD
            value: minio123
          - name: JMX_EXPORTER_ENABLE
            value: "false"
          - name: JMX_EXPORTER_PORT
            value: "9404"
          - name: JMX_EXPORTER_CONFIG
            value: /opt/hive-metastore/conf/jmx-exporter.yaml
          - name: ENABLE_JMX_REMOTE
            value: "false"
          - name: JMX_PORT
            value: "9010"
          - name: JMX_RMI_PORT
            value: "9010"
          - name: DT_ONEAGENT_ENABLE
            value: "false"
          - name: DT_ONEAGENT_PATH
            value: /opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so
        ports: 
          - name: thrift
            containerPort: 9083
          - name: metrics
            containerPort: 9404
          - name: jmx
            containerPort: 9010
        startupProbe:
          tcpSocket:
            port: thrift
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: thrift
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: thrift
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
        volumeMounts:
          - name: fq-hms-configs-volume
            mountPath: /opt/hive-metastore/conf/metastore-site.xml
            subPath: metastore-site.xml
          - name: fq-hms-configs-volume
            mountPath: /opt/hive-metastore/conf/core-site.xml
            subPath: core-site.xml
          - name: fq-hms-configs-volume
            mountPath: /opt/hive-metastore/conf/metastore-log4j2.properties
            subPath: metastore-log4j2.properties
          - name: fq-hms-configs-volume
            mountPath: /opt/hive-metastore/conf/jmx-exporter.yaml
            subPath: jmx-exporter.yaml
        command: ["/opt/hive-metastore/bin/entrypoint.sh"]
        args: ["-p","9083","--skiphadoopversion"]
        imagePullPolicy: Always
      volumes:
        - name: fq-hms-configs-volume
          configMap:
            name: fq-hms-configs
