apiVersion: v1
kind: ServiceAccount
metadata:
  name: fq-network-policy-updater
  namespace: fq
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fq-network-policy-updater-role
rules:
  - apiGroups: ["networking.k8s.io", "cilium.io"]
    resources: ["networkpolicies", "ciliumnetworkpolicies"]
    verbs: ["get", "list", "create", "update", "patch", "apply"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fq-network-policy-updater-binding
subjects:
  - kind: ServiceAccount
    name: fq-network-policy-updater
    namespace: fq
roleRef:
  kind: ClusterRole
  name: fq-network-policy-updater-role
  apiGroup: rbac.authorization.k8s.io
