apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fq

resources:
  - fq-trino-deployment.yml
  - fq-trino-egress-network-policy.yml
  - fq-trino-ingress-network-policy.yml
  - fq-trino-service.yml
  - fq-trino-statefulset.yml
configMapGenerator:
  - name: fq-trino-configs
    files:
      - configs/config.properties.coordinator
      - configs/config.properties.worker
      - configs/node.properties
      - configs/jvm.config
      - password.db
      - configs/password-authenticator.properties
      - configs/access-control.properties
      - configs/rules.json
  - name: fq-trino-datasource-configs
    files:
      - configs/gravitino.properties
      - configs/http.properties
      - configs/hms_db.properties
      - configs/iceberg.properties
      - configs/minio.properties
      - configs/steampipe_db.properties
      - configs/nessie.properties
