apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aix-moat-egress-policy
  namespace: aix
spec:
  podSelector:
    matchLabels:
      app: moat
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app: mysql
      ports:
        - protocol: TCP
          port: 3306
