apiVersion: apps/v1
kind: Deployment
metadata:
  name: moat
  namespace: aix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moat
  template:
    metadata:
      labels:
        app: moat
    spec:
      initContainers:
        - name: init-db
          image: moat:local_0.21.0
          imagePullPolicy: IfNotPresent
          command: ["/app/entrypoint.sh"]
          args: ["migrate", "upgrade"]
          envFrom:
            - secretRef:
                name: moat-env-secret
          env:
            - name: CONFIG_FILE_PATH
              value: "/opt/moat/config.yaml"
          volumeMounts:
            - name: moat-api-config
              mountPath: /opt/moat
      containers:
        - name: api
          image: moat:local_0.21.0
          imagePullPolicy: IfNotPresent
          command: ["/app/entrypoint.sh"]
          args: ["start-server"]
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: moat-env-secret
          env:
            - name: CONFIG_FILE_PATH
              value: "/opt/moat/config.yaml"
          volumeMounts:
            - name: moat-api-config
              mountPath: /opt/moat
              readOnly: true
            - name: moat-config-trino-policy
              mountPath: /opt/moat/trino
              readOnly: true
            - name: bundle-storage
              mountPath: /opt/moat/bundles
        - name: worker
          image: moat:local_0.21.0
          imagePullPolicy: IfNotPresent
          command: ["/app/entrypoint.sh"]
          args: ["start-worker"]
          envFrom:
            - secretRef:
                name: moat-env-secret
          env:
            - name: CONFIG_FILE_PATH
              value: "/opt/moat/config.yaml"
          volumeMounts:
            - name: moat-api-config
              mountPath: /opt/moat
              readOnly: true
            - name: moat-config-trino-policy
              mountPath: /opt/moat/trino
              readOnly: true
            - name: bundle-storage
              mountPath: /opt/moat/bundles
      volumes:
        - name: moat-api-config
          configMap:
            name: moat-api-config
        - name: moat-config-trino-policy
          configMap:
            name: moat-config-trino-policy
        - name: bundle-storage
          emptyDir: {}
