"""adds opa bundle table

Revision ID: 1bc94f0117f4
Revises: e1833e19df8b
Create Date: 2025-09-24 06:47:56.730492+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1bc94f0117f4"
down_revision: Union[str, Sequence[str], None] = "e1833e19df8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opa_bundles",
        sa.Column("opa_bundle_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column("e_tag", sa.String(), nullable=True),
        sa.Column("bundle_filename", sa.String(), nullable=True),
        sa.Column("bundle_directory", sa.String(), nullable=True),
        sa.Column("policy_hash", sa.String(), nullable=True),
        sa.Column(
            "record_updated_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("opa_bundle_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("opa_bundles")
    # ### end Alembic commands ###
