"""initial revision

Revision ID: e73c0de18f01
Revises: 
Create Date: 2025-09-19 06:33:12.431339+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e73c0de18f01"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_logs",
        sa.Column("decision_log_id", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("operation", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("database", sa.String(), nullable=True),
        sa.Column("schema", sa.String(), nullable=True),
        sa.Column("table", sa.String(), nullable=True),
        sa.Column("column", sa.String(), nullable=True),
        sa.Column("permitted", sa.Boolean(), nullable=True),
        sa.Column("expression", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("decision_log_id"),
    )
    op.create_table(
        "ingestion_processes",
        sa.Column(
            "ingestion_process_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("object_type", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("log", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("ingestion_process_id"),
    )
    op.create_table(
        "principal_attributes",
        sa.Column(
            "principal_attribute_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("attribute_key", sa.String(), nullable=True),
        sa.Column("attribute_value", sa.String(), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="t", nullable=True),
        sa.Column(
            "record_updated_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("principal_attribute_id"),
    )
    op.create_table(
        "principal_attributes_history",
        sa.Column("principal_attribute_id", sa.Integer(), nullable=True),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("attribute_key", sa.String(), nullable=True),
        sa.Column("attribute_value", sa.String(), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="t", nullable=True),
        sa.Column(
            "record_updated_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "history_id",
            sa.String(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "history_record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("history_change_operation", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_table(
        "principal_attributes_stg",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("attribute_key", sa.String(), nullable=True),
        sa.Column("attribute_value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "principal_groups",
        sa.Column(
            "principal_group_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("members", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("source_uid", sa.String(), nullable=True),
        sa.Column("scim_payload", sa.JSON(), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="t", nullable=True),
        sa.Column(
            "record_updated_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("principal_group_id"),
    )
    op.create_table(
        "principal_groups_history",
        sa.Column("principal_group_id", sa.Integer(), nullable=True),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("members", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("source_uid", sa.String(), nullable=True),
        sa.Column("scim_payload", sa.JSON(), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="t", nullable=True),
        sa.Column(
            "record_updated_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "history_id",
            sa.String(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "history_record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("history_change_operation", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_table(
        "principals",
        sa.Column("principal_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("user_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("source_uid", sa.String(), nullable=True),
        sa.Column("scim_payload", sa.JSON(), nullable=True),
        sa.Column("entitlements", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="t", nullable=True),
        sa.Column(
            "record_updated_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("principal_id"),
    )
    op.create_table(
        "principals_history",
        sa.Column("principal_id", sa.Integer(), nullable=True),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("user_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("source_uid", sa.String(), nullable=True),
        sa.Column("scim_payload", sa.JSON(), nullable=True),
        sa.Column("entitlements", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="t", nullable=True),
        sa.Column(
            "record_updated_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "history_id",
            sa.String(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "history_record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("history_change_operation", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_table(
        "principals_staging",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("user_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resource_attributes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("attribute_key", sa.String(), nullable=True),
        sa.Column("attribute_value", sa.String(), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="t", nullable=True),
        sa.Column(
            "record_updated_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resource_attributes_history",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("attribute_key", sa.String(), nullable=True),
        sa.Column("attribute_value", sa.String(), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="t", nullable=True),
        sa.Column(
            "record_updated_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "history_id",
            sa.String(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "history_record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("history_change_operation", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_table(
        "resource_attributes_stg",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("attribute_key", sa.String(), nullable=True),
        sa.Column("attribute_value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column("object_type", sa.String(), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="t", nullable=True),
        sa.Column(
            "record_updated_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resources_history",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column("object_type", sa.String(), nullable=True),
        sa.Column("ingestion_process_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="t", nullable=True),
        sa.Column(
            "record_updated_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "history_id",
            sa.String(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "history_record_created_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("history_change_operation", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("history_id"),
    )
    op.create_table(
        "resources_stg",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fq_name", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column("object_type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resources_stg")
    op.drop_table("resources_history")
    op.drop_table("resources")
    op.drop_table("resource_attributes_stg")
    op.drop_table("resource_attributes_history")
    op.drop_table("resource_attributes")
    op.drop_table("principals_staging")
    op.drop_table("principals_history")
    op.drop_table("principals")
    op.drop_table("principal_groups_history")
    op.drop_table("principal_groups")
    op.drop_table("principal_attributes_stg")
    op.drop_table("principal_attributes_history")
    op.drop_table("principal_attributes")
    op.drop_table("ingestion_processes")
    op.drop_table("decision_logs")
    # ### end Alembic commands ###
