apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polaris-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard   # uncomment/set as appropriate for your cluster