apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmetadata-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmetadata-ingestion
  template:
    metadata:
      labels:
        app: openmetadata-ingestion
    spec:
      containers:
        - name: openmetadata-ingestion
          image: openmetadata/ingestion:latest
          env:
            - name: DB_DRIVER_CLASS
              value: com.mysql.cj.jdbc.Driver
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_SCHEME
              value: mysql
            - name: DB_USER
              value: openmetadata
            - name: DB_USER_PASSWORD
              value: openmetadata_password
            - name: DB_USE_SSL
              value: "false"
            - name: OM_DATABASE
              value: openmetadata_db
            - name: TRINO_HOST
              value: trino
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              airflow db init
              airflow webserver
      volumes:
        - name: openmetadata-configmap-volume
          configMap:
            name: openmetadata-config
---
apiVersion: v1
kind: Service
metadata:
  name: openmetadata-ingestion
spec:
  selector:
    app: openmetadata-ingestion
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30880
      targetPort: 8080
  type: NodePort