apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmetadata-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmetadata-server
  template:
    metadata:
      labels:
        app: openmetadata-server
    spec:
      containers:
        - name: openmetadata-server
          image: openmetadata/server:latest
          ports:
            - containerPort: 8585
          env:
            - name: DB_DRIVER_CLASS
              value: com.mysql.cj.jdbc.Driver
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_SCHEME
              value: mysql
            - name: DB_USER
              value: openmetadata
            - name: DB_USER_PASSWORD
              value: openmetadata_password
            - name: DB_USE_SSL
              value: "false"
            - name: DATABASE
              value: openmetadata
            - name: OM_DATABASE
              value: openmetadata
            - name: TRINO_HOST
              value: trino
            - name: SERVER_HOST_API_URL
              value: http://openmetadata-server:8585/api
            - name: PIPELINE_SERVICE_CLIENT_HOST_IP
              value: ""
            - name: PIPELINE_SERVICE_CLIENT_ENDPOINT
              value: http://openmetadata-ingestion:8080
            - name: AIRFLOW_USERNAME
              value: admin
            - name: AIRFLOW_PASSWORD
              value: admin
            - name: PIPELINE_SERVICE_CLIENT_VERIFY_SSL
              value: "no-ssl"
            - name: PIPELINE_SERVICE_CLIENT_SSL_CERT_PATH
              value: ""
            - name: AIRFLOW_TRUST_STORE_PATH
              value: ""

            - name: ELASTICSEARCH_COMPATIBILITY_MODE
              value: "true"
            - name: SEARCH_TYPE
              value: elasticsearch
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_SCHEME
              value: http
          command: [ "/bin/sh", "-c" ]
          #args:
          #  - |
          #    ./bootstrap/openmetadata-ops.sh migrate
          args:
            - |
              ./bootstrap/openmetadata-ops.sh migrate
              ./bin/./openmetadata-server-start.sh ./conf/openmetadata.yaml
      volumes:
        - name: openmetadata-configmap-volume
          configMap:
            name: openmetadata-config
---
apiVersion: v1
kind: Service
metadata:
  name: openmetadata-server
spec:
  selector:
    app: openmetadata-server
  ports:
    - protocol: TCP
      port: 8585
      nodePort: 30085
      targetPort: 8585
  type: NodePort